export const sharedMetadata = {
  title: "Samuel Isah | Full-Stack Developer & Mobile App Creator",
  name: "Samuel Isah",
  description:
    "Full-Stack Web and Mobile Developer creating innovative applications with React, Next.js, React Native, and TypeScript. Specializing in modern web development, mobile apps, and user-centric design solutions.",
  og: "Full-Stack Web and Mobile Developer creating innovative applications with modern technologies.",
  keywords: [
    "Samuel Isah",
    "drealdumore",
    "Full-Stack Developer",
    "Mobile App Developer",
    "React Developer",
    "Next.js Developer",
    "React Native Developer",
    "TypeScript Developer",
    "JavaScript Developer",
    "Frontend Developer",
    "Backend Developer",
    "Web Developer",
    "Software Engineer",
    "UI/UX Developer",
    "Portfolio Website",
    "Creative Developer",
    "Modern Web Development",
    "Responsive Design",
    "Progressive Web Apps",
    "Mobile First Design",
    "Tailwind CSS",
    "Framer Motion",
    "Node.js",
    "API Development",
    "Database Design",
    "Performance Optimization",
    "SEO Optimization",
    "Accessibility",
    "Cross-platform Development",
    "Agile Development",
  ],
  url:
    process.env.NODE_ENV === "development"
      ? "http://localhost:3001"
      : "https://drealdumore.vercel.app",
  ogImage: {
    width: 1200,
    height: 630,
    type: "image/png",
  },
  image: "/og.png",
  author: "Samuel Isah",
  creator: "Samuel Isah",
  publisher: "Samuel Isah",
  category: "Technology",
};